### ISSUE TITLE
Can you update the system requirements in code level?

### ISSUE THREAD

**Issue by jerintk** [dhirendrapratapsingh/ReactApp#1]
Unfortunately I am running Ubuntu 16.04 LTS. When I tried to start the app I am getting some errors. If I try to install the packages again, the system requirements of some packages is not satisfied. Can you fix it? Please check the screenshot attached for more info.
![Screenshot from 2019-04-06 13-52-40](https://user-images.githubusercontent.com/13076834/55666944-58742200-5873-11e9-8a0e-4a690b88f687.png)
![Screenshot from 2019-04-06 13-53-13](https://user-images.githubusercontent.com/13076834/55666945-58742200-5873-11e9-8872-3de3878e9c2d.png)

**Comment by dhirendrapratapsingh** [comment]
I have not system requirememts in code level this is OS compatibility issue

I tried to reproduce the problem wth steps specified in ubntu 16.04 you can see in the steps below
![Screenshot from 2019-04-08 14-55-55](https://user-images.githubusercontent.com/32532380/55714023-80988800-5a0f-11e9-9ee7-0b42a45cdc7d.png)
![Screenshot from 2019-04-08 14-56-38](https://user-images.githubusercontent.com/32532380/55714063-8f7f3a80-5a0f-11e9-88de-7ccca4f8fb0a.png)
![Screenshot from 2019-04-08 14-56-18](https://user-images.githubusercontent.com/32532380/55714074-94dc8500-5a0f-11e9-9072-10de66fd751c.png)

the conclusion can be derived as the npm start is causing problems in ubntu 16,04 because the in inbuilt methods of library react-router-dom is causing problem due to compatiblity with OS as it can be seen in screenshot that react-router-dom is not getting installed.

![Screenshot from 2019-04-08 14-57-17](https://user-images.githubusercontent.com/32532380/55714369-34017c80-5a10-11e9-85bc-3e1ed5e97eba.png)
![Screenshot from 2019-04-08 14-57-25](https://user-images.githubusercontent.com/32532380/55714384-39f75d80-5a10-11e9-8587-5cdf7c98a51c.png)

So this can run only in >=ubntu 18
